fn main() {
    let data = ["abcdef", "bababc", "abbcde", "abcccd", "aabcdd", "abcdee", "ababab"];
    /*let data = ["mphcuiszrnjzxwkbgdzqeoyxfa",
"mihcuisgrnjzxwkbgdtqeoylia",
"mphauisvrnjgxwkbgdtqeiylfa",
"mphcuisnrnjzxwkbgdgqeoylua",
"mphcuisurnjzxwkbgdtqeoilfi",
"mkhcuisvrnjzowkbgdteeoylfa",
"mphcoicvrnjzxwksgdtqeoylfa",
"mxhcuisvrndzxwkbgdtqeeylfa",
"dphcuisijnjzxwkbgdtqeoylfa",
"mihvuisvrqjzxwkbgdtqeoylfa",
"mphcuisrrnvzxwkbgdtqeodlfa",
"mphtuisdrnjzxskbgdtqeoylfa",
"mphcutmvsnjzxwkbgdtqeoylfa",
"mphcunsvrnjzswkggdtqeoylfa",
"mphcuisvrwjzxwkbpdtqeoylfr",
"mphcujsdrnjzxwkbgdtqeovlfa",
"mpfcuisvrdjzxwkbgdtteoylfa",
"mppcuisvrpjzxwkbgdtqeoywfa",
"mphcuisvrnjzxwkbfptqroylfa",
"mphcuisvrnjzxwkbgstoeoysfa",
"mphcufsvrnjzcwkbgdeqeoylfa",
"mphcuissrnjzxwkbgdkquoylfa",
"sphcuxsvrnjzxwkbgdtqioylfa",
"mphcuiivrhjzxwkbgdtqevylfa",
"echcuisvrnjzxwkbgltqeoylfa",
"mphcuisvrljexwkbvdtqeoylfa",
"mpjcuisvrnjzxwkhidtqeoylfa",
"mphcuisvrfjzmwkbgdtqeoylfl",
"mwhcuisvrnjzxwkbgdtqeoytfm",
"mphcuisvrsjzxwkbgdaqeoylfh",
"mohcuisvrnjzxwkbgdtqtoymfa",
"maycuisvrnjzxwkbgdtqboylfa",
"pphcuisvqnjzxwkbgdtqeoylfd",
"mprcuisvrnjtxwmbgdtqeoylfa",
"mfhcuisgrnjzxckbgdtqeoylfa",
"mphiubsvrnjzxwkbgdtqeoyufa",
"dphctisvrnjzxwkbgdtqeoylfk",
"mphcuisvrnjznwksgdtqeoyzfa",
"mpwcuisvrnjziwkbgdtqaoylfa",
"mphduzsvrnjznwkbgdtqeoylfa",
"mphccisvrnjzxwebgdtqeoylqa",
"xphcuisvrnjzxwkfvdtqeoylfa",
"mphcupsvrnjzxwkbgdtfeoylpa",
"mphcuisvrtjzjwkbgdtqeoylfe",
"mpbcuisvrnjzxwkbgdmieoylfa",
"mphcuisvrnjzxwkbgjtqetylaa",
"mphcuisvrnjzxwpbgdtgdoylfa",
"ophcufsvrqjzxwkbgdtqeoylfa",
"iphcuhsvrnjzxwkbgetqeoylfa",
"mphcuisvunjzxwwbgdtqeoylqa",
"mphcpisvrnjzowkbgdtveoylfa",
"mphcuisvrnjzxhkbgdtqeotlla",
"mphcuisvrnjzxwkbodtgeoylha",
"mphcuisvrjjzxwkbwdtqtoylfa",
"mphcwisvrnjnxwkbgjtqeoylfa",
"mplcuicqrnjzxwkbgdtqeoylfa",
"mphcuisvrnjzxydbgdtqeoylfn",
"ophckisvrnjzxwkbgdtqeozlfa",
"mphcuisvrkjzxwkbgdtteoblfa",
"yphcuisvrnjcxwkbggtqeoylfa",
"mphcuisvrnazxwfbqdtqeoylfa",
"mphcuisvrmjzxwkbgdtlwoylfa",
"mphctksvrnjzxwibgdtqeoylfa",
"mphcuisprnjzxlebgdtqeoylfa",
"mphcuisnrnjzxakbgdtueoylfa",
"mphcuiavrnjoxwtbgdtqeoylfa",
"nphcuisvrnjzxwkbgdtqzoylfk",
"mphcuisrrnjmxwkbgdtqdoylfa",
"mphcuisvrujzxwkvgdtqehylfa",
"mphcuisvrnfzxwkogdtqebylfa",
"mphcuisvrnjwdwkbgdtqeoyxfa",
"mphcuisvrntzxwkrgxtqeoylfa",
"mpzcuisvrnjzxwebgdtqeoylsa",
"aphcuikvrnjzxwwbgdtqeoylfa",
"mphcqisvrnjzxwkpgdtqeoelfa",
"mphcuusvrnjzxwkbgdtjeodlfa",
"mphcuisvrnjzewkbgdtteoylza",
"mphcuisvanjzxwkbgdtheoylfc",
"mphcjishrnjzxwkbgltqeoylfa",
"mpxcuislrnjzxwkbgdtqeoynfa",
"mphcuisvrnjjxwkbgdtmeoxlfa",
"mphcimsvrnjzxwkbsdtqeoylfa",
"mphcxisvcnjzxwjbgdtqeoylfa",
"mphcuisbrvjzxwkbgdtqeoymfa",
"mplcuisvrnjzxwkbgdtaenylfa",
"mphcuihvrnjzxwkygytqeoylfa",
"mphcbisvrnjzxhkbgdtqezylfa",
"mphcuisarnjzxwkbgatqeoylfv",
"mphcumsvrnjzxwkbgdrqebylfa",
"mlhcuisvrnwzxwkbgdtqeoylfx",
"mpkcuisvrkjzxwkbgdtqeoylfo",
"mphcuissrnjzxwkbgdtqmoylfc",
"mphcuiwvrnjuxwkfgdtqeoylfa",
"mphcuicvlnjzxwkbgdvqeoylfa",
"mphcuisvrvvzxwkbfdtqeoylfa",
"myhcuisvrnjpxwkbgntqeoylfa",
"mpocuisvrnjzxwtbgitqeoylfa",
"mphcuisvrnjzxwkbgdtwewyqfa",
"mphcuisvtnjzxwwbgdtqeoolfa",
"mphcuisvrnjzxgkbgdyqeoyyfa",
"mphcuisvrdjzxwkbgpyqeoylfa",
"bphcuisvrnjzxwkbgxtqefylfa",
"sphcuisvrdjzxwktgdtqeoylfa",
"mphcuvsvrnjmxwobgdtqeoylfa",
"mphcuisvrnjzxwkbsdtqeuylfb",
"mnhcmisvynjzxwkbgdtqeoylfa",
"mphckisvrnjzxwkhgdkqeoylfa",
"mpacuisvrnjzxwkbgdtqeoolaa",
"mpgcuisvrnjzxwkbzdtqeoynfa",
"mphcuisvrojzxwkbzdtqeoylga",
"mphcuisvknjfxwkbydtqeoylfa",
"mphcuistrnjzxwkbgdqqeuylfa",
"bpvcuiszrnjzxwkbgdtqeoylfa",
"mphcuxsvrnjzswkbgdtqeoelfa",
"mphcuisvbnjzxwlbgdtqeoylla",
"mphcuisvonczxwkbgktqeoylfa",
"mphcuisvrnkzxwvbgdtquoylfa",
"mphcuisvrnjzxokfgdtqeoylia",
"tphcuisvrnjzxwkbjdwqeoylfa",
"mihcuisvrnjzpwibgdtqeoylfa",
"mphcuisvrejzxwkbgdtqjuylfa",
"mprcuisvrnjixwkxgdtqeoylfa",
"mpqcuiszrnjzxwkbgdtqeodlfa",
"mphcuasvrnjzzakbgdtqeoylva",
"mphcuisvrnjzmwkbtdtqeoycfa",
"mphcuisvrnjzxwkbcdtqioylxa",
"mphckisvrnjzxwkbcdtqeoylfm",
"mphcuisvrnjuxwbogdtqeoylfa",
"mphcuisdrnjzxwkbldtqeoylfx",
"mphcuisvrnjoxwkbgdtqeyyyfa",
"mphcuicvqnjzxwkbgdtqeoylna",
"mpmcuisvrnjzxwkbgdtqktylfa",
"mphcuisvrnqzxwkggdtqeoykfa",
"mphcuisvryjzxwkbydtqejylfa",
"mphcugsvrnjzxwkbghtqeeylfa",
"rphcuusvrnjzxwkwgdtqeoylfa",
"zphwuiyvrnjzxwkbgdtqeoylfa",
"cphcuivvrnjzxwkbgdtqenylfa",
"mphcuisvrnjzxwkagotqevylfa",
"mprcuisvrcjzxwkbgdtqeoytfa",
"mphjugsvrnezxwkbgdtqeoylfa",
"mphcuisvryjzxwkbgltqeoylaa",
"mphcursvrnjzxfkbgdtqeoydfa",
"mphcuisvrcuzxwkbgdtqeoylfw",
"mphcuisvrijzxwkbgdtqeoelfh",
"xphcuisvenjzxjkbgdtqeoylfa",
"mphcuisvrnazxwkbgdeqeoylaa",
"mphcuisbrsjzxwkbgdtqeoygfa",
"mlhvuisvrnjzxwkbgdtqeoylfh",
"mphcuisvrnjzxukbgdtqeoyhfy",
"mpzcuilvrnjzawkbgdtqeoylfa",
"hphcuisjfnjzxwkbgdtqeoylfa",
"mahcuisvrnjzxwkegdtqeoylfi",
"mphcuixvrnjzcwkbgdtqetylfa",
"mphcuisvrnjzxwkdgdtqeoklfj",
"mlhcuisvrnjzxwkbgdteeoylka",
"mphcuifvrnjbxwkrgdtqeoylfa",
"mphcuasvrnjzzwkbgdtqeoylva",
"mphcuisvrnjzxwkboutqeoylba",
"mbhcuisvcnjzxwklgdtqeoylfa",
"mpbcuisvrnjzxgkbgdtqesylfa",
"mphcuisvrnjfswkbgdtqeoylfd",
"mphcuisvrnjzxwkbgdoweoysfa",
"uphcuisvrnjzrwkbgdtqelylfa",
"mphcuisvrnjzxwkbgdtqyoylsi",
"mpqcuiqvxnjzxwkbgdtqeoylfa",
"mphcuisorfjzxwkbgatqeoylfa",
"mphcuisvrntfxwkbzdtqeoylfa",
"mphcuisvrnrzxwkbgdtueoylfl",
"mphcuisvrnjzewkagdtyeoylfa",
"mpocuisdrnjzxwkbgdtqeozlfa",
"mphcuisvrnjjxwkbgdtoeoylfm",
"mphcuisvenjzxwkbgdtqwoylza",
"mpmcuisvrnjzxwkbgdtqeoxlfr",
"mphcuisvgnjhxwkbgdtqeoplfa",
"mphcuisvrnjzowkdgdtqeoyyfa",
"mphcuisqynjzxwkbgdtqeoylda",
"hphcuisvgnjzxwkbgdtbeoylfa",
"iphcuipvrnuzxwkbgdtqeoylfa",
"mphcuisvrnjzsikbpdtqeoylfa",
"mpwcuhsvrnjzxbkbgdtqeoylfa",
"mnhjuisvcnjzxwkbgdtqeoylfa",
"mphcudsvrnjzxwkbgdtqloilfa",
"mpncuiwvrwjzxwkbgdtqeoylfa",
"mphcuisvrnjgawkbgdtqeoylya",
"mphcuisvrnjzxwkbggtteoslfa",
"mphcuisvrnjzxwkbgdvqeoylpe",
"mphcuisvrnczxfkbgktqeoylfa",
"mphcuifvrnjzxwkbgdbmeoylfa",
"mphcuisvrnjytwkbgdtqeoylla",
"mphcuisvrnjzxwkbgdtjeoxlfn",
"mphjuisvrnjzxwkbghtqeoyffa",
"mphcuisvrnjzxkrbgdtqeoylaa",
"mphcbisvrnjzxwkbgttqeoylfs",
"mphkuksvbnjzxwkbgdtqeoylfa",
"nphcuidvrnjzxwhbgdtqeoylfa",
"mphguzsvrnjzxwkbgdaqeoylfa",
"mihcuisfrnjzxwkbgdtqhoylfa",
"mphcuisvrnrzxwpbgdtqesylfa",
"zphcuisvrnjzxwkbddtqeoylaa",
"mphcuigvmnjzxwkbgdtqeoylba",
"mjhcuisvrnjzxjkbgdtqeoylha",
"mphnuisvrnjznwkbgdtqnoylfa",
"mkhcuisvrnjcxwkbgdqqeoylfa",
"mphcuisvenjzxwbbqdtqeoylfa",
"qphcuisnrnjzawkbgdtqeoylfa",
"mphcuisvrdjzxwkbgdtqeoywca",
"mphcuzsvvnjzxwfbgdtqeoylfa",
"pphcuxsvrnjzxwkbgdtmeoylfa",
"mphiuvsvrnjzxlkbgdtqeoylfa",
"mphlqisvrnjzxkkbgdtqeoylfa",
"mmhcuisvrnjzxwkbgatqeoylea",
"mphduisrrnjoxwkbgdtqeoylfa",
"mphcuisvrnjnxwkvgdyqeoylfa",
"mphcuvsvrnjzxgkbgdtqeoylfz",
"mphcuisvryjzxwkbggtqkoylfa",
"iphcuisvrdjzxwkbgotqeoylfa",
"mphcuisvrnjzxwhbgdtqwoyofa",
"mphcorbvrnjzxwkbgdtqeoylfa",
"mghcuisvrnpzxykbgdtqeoylfa",
"mphauisvrnjnxwkbzdtqeoylfa",
"mphcgisvrnjzxwkwgdtqeoygfa",
"mphcuisvrnjzxwkggotqeoylba",
"mphcuesvrnjzxwkbgdwqebylfa",
"yphcuisvrnjzxwkbgdxqeoylja",
"ephyuisvrnjzywkbgdtqeoylfa",
"mfhcuisqrnjzxwkbgdlqeoylfa",
"mphkuisvrnjzxwkbertqeoylfa",
"mphcuusgrnjzxwkbggtqeoylfa",
"mphcuildrnjvxwkbgdtqeoylfa",
"mphcuiuvrnjzlwkbgwtqeoylfa",
"mppcuisvrljzxwkbgdtqeoylfw",
"mphcwiwvrnjzxwsbgdtqeoylfa",
"mphcubivrnjzxwkqgdtqeoylfa",
"mphcuisvrnjpxwkngdtqeoylpa",
"pchcuisvrgjzxwkbgdtqeoylfa",
"mphcuisvlnjzxwkbgdtmeoylfw",
"mphcuisvrnjzywkbgdvqeoylfj",
"mpzcuisvrnezxwktgdtqeoylfa",
"mphcuisvrnjbxwkbgzrqeoylfa",
"mphcuisvrnjzxwktgdtqeodtfa",
"jphcuiavrnjzxwkbgdtqeoylfv",
"mphcuisvrnjzxwkbddppeoylfa",
"mphcuissrkjzxwkbgxtqeoylfa",
"mphcuisvrhjzxwxbgdtqeoylxa",
"mphcvisvgnjjxwkbgdtqeoylfa",
"mphcuisprnjwxwtbgdtqeoylfa",
"mphcuissrnjzxqkbgdtqeoymfa",
"mphcuiabrnjzxokbgdtqeoylfa",
"mphcuisvrnczxwkbgmtpeoylfa"];*/

    let mut contador_doble = 0;
    let mut contador_triple =0;

    for i in 0..data.len(){ //ciclo del arreglo
        let mut contador = vec![0 ; data[i].len()];
        let mut bandera_triple = 0;
        let mut bandera_doble = 0;
        for x in 0..data[i].len(){ //ciclo de la letra a comparar
            for a in x..data[i].len(){ //ciclo de comparación con el resto de las letras
                if data[i].chars().nth(x).unwrap() == data[i].chars().nth(a).unwrap(){
                    contador[x] +=1;
                }
                //println!("{}",data[i].chars().nth(a).unwrap());
            }
                println!("{} ", contador[x]);
                if contador[x] == 2 {
                    //contador_doble += 1;
                    bandera_doble += 1;
                //    println!("dos");
                //    println!("{}",data[i].chars().nth(*r).unwrap());
            } else if contador[x] == 3 {
                    //contador_triple += 1;
                    bandera_triple += 1;
                //    println!("tres");
                }
                //println!("------------------------------------------------------");

        }
        bandera_doble -= bandera_triple;

        if bandera_triple > 0 {
            contador_triple += 1;
        }
        if bandera_doble > 0 {
            contador_doble += 1;
        }
        println!("El Checksum es de {} x {}", contador_doble, contador_triple);
    }
    println!("El Checksum es de {} x {} = {}", contador_doble, contador_triple, contador_doble * contador_triple);

}
